language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-6.1
  - Pharo-5.0
  
before_script:
  #/tmp does not exist in travis by default
  #To make tests run correctly, create /tmp before running the scripts
  #https://stackoverflow.com/questions/39265413/trouble-with-tmp-directory-on-travis
  #https://stackoverflow.com/questions/19253031/heroku-how-to-write-into-tmp-directory
  - mkdir -p /tmp