language: smalltalk

sudo: false

os:
  - linux
  - osx
  
smalltalk:
  - Pharo64-10
  - Pharo64-9.0
# Waiting a 32-bit version of Pharo 90 before re-enabling this version
#  - Pharo32-9.0

env:
  matrix:
    - CI_FILE=.smalltalk.ston
    - CI_FILE=.stress.smalltalk.ston

before_script:
  - mkdir -p $SMALLTALK_CI_BUILD/UCD && cp UCD/* $SMALLTALK_CI_BUILD/UCD/

script:
  - travis_wait 60 $SMALLTALK_CI_HOME/run.sh ${CI_FILE}
