language: smalltalk

sudo: false

os:
  - linux
  - osx
  
smalltalk:
  - Pharo64-8.0
  - Pharo64-7.0
  - Pharo32-8.0
  - Pharo32-7.0

env:
  matrix:
    - CI_FILE=.smalltalk.ston
    - CI_FILE=.stress.smalltalk.ston
    
script:
  - travis_wait 120 sleep infinity &
  - $SMALLTALK_CI_HOME/run.sh ${CI_FILE}
