language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-alpha
  - Pharo-6.1
  - Pharo-5.0
  
smalltalk_config:
  - .smalltalk.ston
  - .stress.smalltalk.ston
  
matrix:
  include:
    - smalltalk: Pharo-alpha
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo-6.1
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo-5.0
      smalltalk_config: .smalltalk.ston
    - smalltalk: Pharo-alpha
      smalltalk_config: .stress.smalltalk.ston
    - smalltalk: Pharo-6.1
      smalltalk_config: .stress.smalltalk.ston
    - smalltalk: Pharo-5.0
      smalltalk_config: .stress.smalltalk.ston
